definitions:
  domain.Odontologo:
    properties:
      apellidoOdontologo:
        type: string
      idOdontologo:
        type: integer
      matriculaOdontologo:
        type: string
      nombreOdontologo:
        type: string
    required:
    - apellidoOdontologo
    - matriculaOdontologo
    - nombreOdontologo
    type: object
  domain.Paciente:
    properties:
      apellidoPaciente:
        type: string
      dniPaciente:
        type: string
      domicilioPaciente:
        type: string
      fechaDeAltaPaciente:
        type: string
      idPaciente:
        type: integer
      nombrePaciente:
        type: string
    required:
    - apellidoPaciente
    - dniPaciente
    - domicilioPaciente
    - fechaDeAltaPaciente
    - nombrePaciente
    type: object
  domain.Turno:
    properties:
      descripcionTurno:
        type: string
      fechaTurno:
        type: string
      idOdontologo:
        type: string
      idPaciente:
        type: string
      idTurno:
        type: integer
    required:
    - descripcionTurno
    - fechaTurno
    - idOdontologo
    - idPaciente
    type: object
  handler.Request:
    properties:
      apellidoOdontologo:
        type: string
      matriculaOdontologo:
        type: string
      nombreOdontologo:
        type: string
    type: object
  web.errorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  web.response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact:
    name: API Support
  description: Reserva de turnos odontológicos
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.ctd.com.ar/es_ar/terminos-y-condiciones
  title: Api de turnos Odontologicos
  version: "1.0"
paths:
  /api/v1/odontologos:
    post:
      description: Crea un nuevo odontólogo con los datos proporcionados
      parameters:
      - description: Datos del odontólogo a crear
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Odontologo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Crear un nuevo odontólogo
      tags:
      - Odontologos
  /api/v1/odontologos/{idOdontologo}:
    delete:
      description: Elimina un odontólogo por su ID
      parameters:
      - description: ID del odontólogo a eliminar
        in: path
        name: idOdontologo
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Eliminar un odontólogo por ID
      tags:
      - Odontologos
    get:
      description: Obtiene un odontologo por su ID
      parameters:
      - description: ID del odontólogo a obtener
        in: path
        name: idOdontologo
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener un odontologo por ID
      tags:
      - Odontologos
    patch:
      description: Actualiza parcialmente un odontólogo por su ID con campos específicos
      parameters:
      - description: ID del odontólogo a actualizar
        in: path
        name: idOdontologo
        required: true
        type: integer
      - description: Campos a actualizar
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar parcialmente un odontólogo por ID
      tags:
      - Odontologos
    put:
      description: Actualiza un odontólogo por su ID con todos los campos
      parameters:
      - description: ID del odontólogo a actualizar
        in: path
        name: idOdontologo
        required: true
        type: integer
      - description: Datos del odontólogo a actualizar
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Odontologo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar un odontólogo por ID
      tags:
      - Odontologos
  /api/v1/pacientes:
    post:
      consumes:
      - application/json
      description: Crea un nuevo paciente
      parameters:
      - description: Datos del paciente a crear
        in: body
        name: paciente
        required: true
        schema:
          $ref: '#/definitions/domain.Paciente'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Crear un nuevo paciente
      tags:
      - Pacientes
  /api/v1/pacientes/{idPaciente}:
    delete:
      consumes:
      - application/json
      description: Elimina un paciente por su ID
      parameters:
      - description: ID del paciente a eliminar
        in: path
        name: idPaciente
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Eliminar un paciente por ID
      tags:
      - Pacientes
    get:
      consumes:
      - application/json
      description: Obtiene un paciente por su ID
      parameters:
      - description: ID del paciente a obtener
        in: path
        name: idPaciente
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener un paciente por ID
      tags:
      - Pacientes
    patch:
      consumes:
      - application/json
      description: Actualiza parcialmente un paciente por su ID con campos específicos
      parameters:
      - description: ID del paciente a actualizar
        in: path
        name: idPaciente
        required: true
        type: integer
      - description: Campos a actualizar
        in: body
        name: paciente
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar parcialmente un paciente por ID
      tags:
      - Pacientes
    put:
      consumes:
      - application/json
      description: Actualiza un paciente por su ID con todos los campos
      parameters:
      - description: ID del paciente a actualizar
        in: path
        name: idPaciente
        required: true
        type: integer
      - description: Datos del paciente a actualizar
        in: body
        name: paciente
        required: true
        schema:
          $ref: '#/definitions/domain.Paciente'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar un paciente por ID
      tags:
      - Pacientes
  /api/v1/turnos/{idTurno}:
    delete:
      consumes:
      - application/json
      description: Elimina un turno por su ID
      parameters:
      - description: ID del turno a eliminar
        in: path
        name: idTurno
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Eliminar un turno
      tags:
      - Turnos
    get:
      consumes:
      - application/json
      description: Retorna un turno dado su ID
      parameters:
      - description: ID del turno a obtener
        in: path
        name: idTurno
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener turno por ID
      tags:
      - Turnos
    patch:
      consumes:
      - application/json
      description: Actualiza campos específicos de un turno por su ID
      parameters:
      - description: ID del turno a actualizar
        in: path
        name: idTurno
        required: true
        type: integer
      - description: Campos a actualizar del turno
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar campos específicos de un turno
      tags:
      - Turnos
    post:
      consumes:
      - application/json
      description: Retorna un turno dado su ID
      parameters:
      - description: ID del turno a obtener
        in: path
        name: idTurno
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Obtener turno por ID
      tags:
      - Turnos
    put:
      consumes:
      - application/json
      description: Actualiza un turno existente por su ID
      parameters:
      - description: ID del turno a actualizar
        in: path
        name: idTurno
        required: true
        type: integer
      - description: Información actualizada del turno
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Turno'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Actualizar turno
      tags:
      - Turnos
swagger: "2.0"
